import type { Metadata } from 'next'
import './globals.css'
import { cn } from '@/lib/utils'
import { Kanit, Montserrat } from 'next/font/google'
import AuthProvider from '@/components/ui/providers/session'

const kanit = Kanit({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap',
})

const montserrat = Montserrat({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background antialiased',
          kanit.className,
        )}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
